#if SDS12_5
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.ballytech.com/sds/asset", ClrNamespace="www.ballytech.com.sds.asset")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ballytech.com/sds/asset", ConfigurationName="AssetEndPoint")]
public interface AssetEndPoint
{
    
    // CODEGEN: Generating message contract since the operation createTermianl is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.ballytech.com.sds.asset.SWSException), Action="", Name="SWSException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    createTermianlResponse1 createTermianl(createTermianlRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class createTermianl
{
    
    private int arg0Field;
    
    private string arg1Field;
    
    private string arg2Field;
    
    private string arg3Field;
    
    private string arg4Field;
    
    private int arg5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string arg1
    {
        get
        {
            return this.arg1Field;
        }
        set
        {
            this.arg1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string arg2
    {
        get
        {
            return this.arg2Field;
        }
        set
        {
            this.arg2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string arg3
    {
        get
        {
            return this.arg3Field;
        }
        set
        {
            this.arg3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string arg4
    {
        get
        {
            return this.arg4Field;
        }
        set
        {
            this.arg4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public int arg5
    {
        get
        {
            return this.arg5Field;
        }
        set
        {
            this.arg5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class organizationDTO
{
    
    private long createdTsField;
    
    private string createdUserField;
    
    private long deletedTsField;
    
    private string deletedUserField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string longNameField;
    
    private int organizationParentIdField;
    
    private bool organizationParentIdFieldSpecified;
    
    private short organizationTypeIdField;
    
    private bool organizationTypeIdFieldSpecified;
    
    private string shortNameField;
    
    private long updatedTsField;
    
    private string updatedUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public long createdTs
    {
        get
        {
            return this.createdTsField;
        }
        set
        {
            this.createdTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string createdUser
    {
        get
        {
            return this.createdUserField;
        }
        set
        {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public long deletedTs
    {
        get
        {
            return this.deletedTsField;
        }
        set
        {
            this.deletedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string deletedUser
    {
        get
        {
            return this.deletedUserField;
        }
        set
        {
            this.deletedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string longName
    {
        get
        {
            return this.longNameField;
        }
        set
        {
            this.longNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public int organizationParentId
    {
        get
        {
            return this.organizationParentIdField;
        }
        set
        {
            this.organizationParentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool organizationParentIdSpecified
    {
        get
        {
            return this.organizationParentIdFieldSpecified;
        }
        set
        {
            this.organizationParentIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public short organizationTypeId
    {
        get
        {
            return this.organizationTypeIdField;
        }
        set
        {
            this.organizationTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool organizationTypeIdSpecified
    {
        get
        {
            return this.organizationTypeIdFieldSpecified;
        }
        set
        {
            this.organizationTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string shortName
    {
        get
        {
            return this.shortNameField;
        }
        set
        {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public long updatedTs
    {
        get
        {
            return this.updatedTsField;
        }
        set
        {
            this.updatedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string updatedUser
    {
        get
        {
            return this.updatedUserField;
        }
        set
        {
            this.updatedUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class siteDTO
{
    
    private string address1Field;
    
    private string address2Field;
    
    private string address3Field;
    
    private string cityField;
    
    private string countryField;
    
    private long createdTsField;
    
    private string createdUserField;
    
    private bool defaultField;
    
    private long deletedTsField;
    
    private string deletedUserField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private areaDTO[] listAreaDTOField;
    
    private string longNameField;
    
    private string numberField;
    
    private organizationDTO organizationField;
    
    private int organizationIdField;
    
    private bool organizationIdFieldSpecified;
    
    private string phoneField;
    
    private string shortNameField;
    
    private string stateProvinceRegionField;
    
    private long updatedTsField;
    
    private string updatedUserField;
    
    private string zipPostalCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string address1
    {
        get
        {
            return this.address1Field;
        }
        set
        {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string address2
    {
        get
        {
            return this.address2Field;
        }
        set
        {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string address3
    {
        get
        {
            return this.address3Field;
        }
        set
        {
            this.address3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public long createdTs
    {
        get
        {
            return this.createdTsField;
        }
        set
        {
            this.createdTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string createdUser
    {
        get
        {
            return this.createdUserField;
        }
        set
        {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public bool @default
    {
        get
        {
            return this.defaultField;
        }
        set
        {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public long deletedTs
    {
        get
        {
            return this.deletedTsField;
        }
        set
        {
            this.deletedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string deletedUser
    {
        get
        {
            return this.deletedUserField;
        }
        set
        {
            this.deletedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("listAreaDTO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
    public areaDTO[] listAreaDTO
    {
        get
        {
            return this.listAreaDTOField;
        }
        set
        {
            this.listAreaDTOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string longName
    {
        get
        {
            return this.longNameField;
        }
        set
        {
            this.longNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public organizationDTO organization
    {
        get
        {
            return this.organizationField;
        }
        set
        {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    public int organizationId
    {
        get
        {
            return this.organizationIdField;
        }
        set
        {
            this.organizationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool organizationIdSpecified
    {
        get
        {
            return this.organizationIdFieldSpecified;
        }
        set
        {
            this.organizationIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
    public string shortName
    {
        get
        {
            return this.shortNameField;
        }
        set
        {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
    public string stateProvinceRegion
    {
        get
        {
            return this.stateProvinceRegionField;
        }
        set
        {
            this.stateProvinceRegionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
    public long updatedTs
    {
        get
        {
            return this.updatedTsField;
        }
        set
        {
            this.updatedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
    public string updatedUser
    {
        get
        {
            return this.updatedUserField;
        }
        set
        {
            this.updatedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
    public string zipPostalCode
    {
        get
        {
            return this.zipPostalCodeField;
        }
        set
        {
            this.zipPostalCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class areaDTO
{
    
    private int areaParentIdField;
    
    private bool areaParentIdFieldSpecified;
    
    private areaTypeDTO areaTypeDTOField;
    
    private short areaTypeIdField;
    
    private bool areaTypeIdFieldSpecified;
    
    private long createdTsField;
    
    private string createdUserField;
    
    private long deletedTsField;
    
    private string deletedUserField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string longNameField;
    
    private int maxAreaIdField;
    
    private bool maxAreaIdFieldSpecified;
    
    private string shortNameField;
    
    private siteDTO siteDTOField;
    
    private int siteIdField;
    
    private bool siteIdFieldSpecified;
    
    private long updatedTsField;
    
    private string updatedUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int areaParentId
    {
        get
        {
            return this.areaParentIdField;
        }
        set
        {
            this.areaParentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaParentIdSpecified
    {
        get
        {
            return this.areaParentIdFieldSpecified;
        }
        set
        {
            this.areaParentIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public areaTypeDTO areaTypeDTO
    {
        get
        {
            return this.areaTypeDTOField;
        }
        set
        {
            this.areaTypeDTOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public short areaTypeId
    {
        get
        {
            return this.areaTypeIdField;
        }
        set
        {
            this.areaTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool areaTypeIdSpecified
    {
        get
        {
            return this.areaTypeIdFieldSpecified;
        }
        set
        {
            this.areaTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public long createdTs
    {
        get
        {
            return this.createdTsField;
        }
        set
        {
            this.createdTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string createdUser
    {
        get
        {
            return this.createdUserField;
        }
        set
        {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public long deletedTs
    {
        get
        {
            return this.deletedTsField;
        }
        set
        {
            this.deletedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string deletedUser
    {
        get
        {
            return this.deletedUserField;
        }
        set
        {
            this.deletedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string longName
    {
        get
        {
            return this.longNameField;
        }
        set
        {
            this.longNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public int maxAreaId
    {
        get
        {
            return this.maxAreaIdField;
        }
        set
        {
            this.maxAreaIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxAreaIdSpecified
    {
        get
        {
            return this.maxAreaIdFieldSpecified;
        }
        set
        {
            this.maxAreaIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public string shortName
    {
        get
        {
            return this.shortNameField;
        }
        set
        {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public siteDTO siteDTO
    {
        get
        {
            return this.siteDTOField;
        }
        set
        {
            this.siteDTOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public int siteId
    {
        get
        {
            return this.siteIdField;
        }
        set
        {
            this.siteIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool siteIdSpecified
    {
        get
        {
            return this.siteIdFieldSpecified;
        }
        set
        {
            this.siteIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public long updatedTs
    {
        get
        {
            return this.updatedTsField;
        }
        set
        {
            this.updatedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public string updatedUser
    {
        get
        {
            return this.updatedUserField;
        }
        set
        {
            this.updatedUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class areaTypeDTO
{
    
    private long createdTsField;
    
    private string createdUserField;
    
    private long deletedTsField;
    
    private string deletedUserField;
    
    private short idField;
    
    private bool idFieldSpecified;
    
    private string labelKeyField;
    
    private string nameField;
    
    private long updatedTsField;
    
    private string updatedUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public long createdTs
    {
        get
        {
            return this.createdTsField;
        }
        set
        {
            this.createdTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string createdUser
    {
        get
        {
            return this.createdUserField;
        }
        set
        {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public long deletedTs
    {
        get
        {
            return this.deletedTsField;
        }
        set
        {
            this.deletedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string deletedUser
    {
        get
        {
            return this.deletedUserField;
        }
        set
        {
            this.deletedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public short id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string labelKey
    {
        get
        {
            return this.labelKeyField;
        }
        set
        {
            this.labelKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public long updatedTs
    {
        get
        {
            return this.updatedTsField;
        }
        set
        {
            this.updatedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string updatedUser
    {
        get
        {
            return this.updatedUserField;
        }
        set
        {
            this.updatedUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class assetNonslotDTO
{
    
    private areaDTO areaDTOField;
    
    private short assetTypeIdField;
    
    private bool assetTypeIdFieldSpecified;
    
    private string assetTypeLabelKeyField;
    
    private string assetTypeNameField;
    
    private string controllerTypeField;
    
    private System.DateTime createdTsField;
    
    private bool createdTsFieldSpecified;
    
    private string createdUserField;
    
    private System.DateTime deletedTsField;
    
    private bool deletedTsFieldSpecified;
    
    private string deletedUserField;
    
    private bool execFineField;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string ipaddressField;
    
    private string locationField;
    
    private string nameField;
    
    private string numberField;
    
    private short terminalEndPointFlgField;
    
    private bool terminalEndPointFlgFieldSpecified;
    
    private int terminalEndPointIdField;
    
    private bool terminalEndPointIdFieldSpecified;
    
    private string terminalIPPortField;
    
    private string terminalLocDescField;
    
    private string terminalMacAddressField;
    
    private string terminalMiscDesc1Field;
    
    private string terminalMiscDesc2Field;
    
    private int terminalSiteIdField;
    
    private bool terminalSiteIdFieldSpecified;
    
    private System.DateTime updatedTsField;
    
    private bool updatedTsFieldSpecified;
    
    private string updatedUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public areaDTO areaDTO
    {
        get
        {
            return this.areaDTOField;
        }
        set
        {
            this.areaDTOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public short assetTypeId
    {
        get
        {
            return this.assetTypeIdField;
        }
        set
        {
            this.assetTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool assetTypeIdSpecified
    {
        get
        {
            return this.assetTypeIdFieldSpecified;
        }
        set
        {
            this.assetTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string assetTypeLabelKey
    {
        get
        {
            return this.assetTypeLabelKeyField;
        }
        set
        {
            this.assetTypeLabelKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string assetTypeName
    {
        get
        {
            return this.assetTypeNameField;
        }
        set
        {
            this.assetTypeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string controllerType
    {
        get
        {
            return this.controllerTypeField;
        }
        set
        {
            this.controllerTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public System.DateTime createdTs
    {
        get
        {
            return this.createdTsField;
        }
        set
        {
            this.createdTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdTsSpecified
    {
        get
        {
            return this.createdTsFieldSpecified;
        }
        set
        {
            this.createdTsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string createdUser
    {
        get
        {
            return this.createdUserField;
        }
        set
        {
            this.createdUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public System.DateTime deletedTs
    {
        get
        {
            return this.deletedTsField;
        }
        set
        {
            this.deletedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deletedTsSpecified
    {
        get
        {
            return this.deletedTsFieldSpecified;
        }
        set
        {
            this.deletedTsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string deletedUser
    {
        get
        {
            return this.deletedUserField;
        }
        set
        {
            this.deletedUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public bool execFine
    {
        get
        {
            return this.execFineField;
        }
        set
        {
            this.execFineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
    public string ipaddress
    {
        get
        {
            return this.ipaddressField;
        }
        set
        {
            this.ipaddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
    public string location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
    public string number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
    public short terminalEndPointFlg
    {
        get
        {
            return this.terminalEndPointFlgField;
        }
        set
        {
            this.terminalEndPointFlgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool terminalEndPointFlgSpecified
    {
        get
        {
            return this.terminalEndPointFlgFieldSpecified;
        }
        set
        {
            this.terminalEndPointFlgFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
    public int terminalEndPointId
    {
        get
        {
            return this.terminalEndPointIdField;
        }
        set
        {
            this.terminalEndPointIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool terminalEndPointIdSpecified
    {
        get
        {
            return this.terminalEndPointIdFieldSpecified;
        }
        set
        {
            this.terminalEndPointIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
    public string terminalIPPort
    {
        get
        {
            return this.terminalIPPortField;
        }
        set
        {
            this.terminalIPPortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
    public string terminalLocDesc
    {
        get
        {
            return this.terminalLocDescField;
        }
        set
        {
            this.terminalLocDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
    public string terminalMacAddress
    {
        get
        {
            return this.terminalMacAddressField;
        }
        set
        {
            this.terminalMacAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
    public string terminalMiscDesc1
    {
        get
        {
            return this.terminalMiscDesc1Field;
        }
        set
        {
            this.terminalMiscDesc1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
    public string terminalMiscDesc2
    {
        get
        {
            return this.terminalMiscDesc2Field;
        }
        set
        {
            this.terminalMiscDesc2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
    public int terminalSiteId
    {
        get
        {
            return this.terminalSiteIdField;
        }
        set
        {
            this.terminalSiteIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool terminalSiteIdSpecified
    {
        get
        {
            return this.terminalSiteIdFieldSpecified;
        }
        set
        {
            this.terminalSiteIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
    public System.DateTime updatedTs
    {
        get
        {
            return this.updatedTsField;
        }
        set
        {
            this.updatedTsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedTsSpecified
    {
        get
        {
            return this.updatedTsFieldSpecified;
        }
        set
        {
            this.updatedTsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
    public string updatedUser
    {
        get
        {
            return this.updatedUserField;
        }
        set
        {
            this.updatedUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ballytech.com/sds/asset")]
public partial class createTermianlResponse
{
    
    private assetNonslotDTO returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public assetNonslotDTO @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createTermianlRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ballytech.com/sds/asset", Order=0)]
    public createTermianl createTermianl;
    
    public createTermianlRequest()
    {
    }
    
    public createTermianlRequest(createTermianl createTermianl)
    {
        this.createTermianl = createTermianl;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createTermianlResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ballytech.com/sds/asset", Order=0)]
    public createTermianlResponse createTermianlResponse;
    
    public createTermianlResponse1()
    {
    }
    
    public createTermianlResponse1(createTermianlResponse createTermianlResponse)
    {
        this.createTermianlResponse = createTermianlResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface AssetEndPointChannel : AssetEndPoint, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AssetEndPointClient : System.ServiceModel.ClientBase<AssetEndPoint>, AssetEndPoint
{
    
    public AssetEndPointClient()
    {
    }
    
    public AssetEndPointClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AssetEndPointClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AssetEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AssetEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createTermianlResponse1 AssetEndPoint.createTermianl(createTermianlRequest request)
    {
        return base.Channel.createTermianl(request);
    }
    
    public createTermianlResponse createTermianl(createTermianl createTermianl1)
    {
        createTermianlRequest inValue = new createTermianlRequest();
        inValue.createTermianl = createTermianl1;
        createTermianlResponse1 retVal = ((AssetEndPoint)(this)).createTermianl(inValue);
        return retVal.createTermianlResponse;
    }
}
namespace www.ballytech.com.sds.asset
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SWSException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SWSException", "http://www.ballytech.com/sds/asset");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
#endif